language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - sudo apt-get update > /dev/null

install:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "127.0.0.1 gallery-bundle.dev" | sudo tee -a /etc/hosts
    - sudo apt-get install -y --force-yes php5-sqlite

before_script:
    - nohup php -S gallery-bundle.dev:8080 -t features/fixtures/project/web > server.log 2>&1 &    

script:
    - composer self-update
    - composer install -n --prefer-source
    - ./bin/phpspec run -f pretty
    - ./bin/behat --no-snippets --verbose --format=progress
    
after_failure:
    - cat server.log

notifications:
  irc: "irc.freenode.org#fsi-open"
